### ISSUE TITLE
Weird import

### ISSUE THREAD

**Issue by channoh** [garion9013/ep-py#1]
이름이 ep-py인데 왜 parser, tools, plotter를 import 해야하지?
그냥 import ep 하면 안됨?

**Comment by younghwanoh** [comment]
python이 그게 되는지 모르겠어요ㅋㅋ
head.py에서
import a,b,c
하고 실제로 쓸 때,
import head
하면 a,b,c가 같이 들어와야되는데 이게 안되는 것 같았네요

**Comment by channoh** [comment]
[https://docs.python.org/2/tutorial/modules.html#packages](https://docs.python.org/2/tutorial/modules.html#packages)
이런건 어때?

**Comment by younghwanoh** [comment]
좋네요~! 한번 볼께요~ㅋㅋㅋ
